// ===== THIS FILE IS GENERATED FROM A TEMPLATE ===== //
// ============== DO NOT EDIT DIRECTLY ============== //

#pragma once

#include "zaber/motion/dto/ascii/alert_event.h"
#include "zaber/motion/dto/ascii/axis_identity.h"
#include "zaber/motion/dto/ascii/axis_type.h"
#include "zaber/motion/dto/ascii/can_set_state_axis_response.h"
#include "zaber/motion/dto/ascii/can_set_state_device_response.h"
#include "zaber/motion/dto/ascii/conversion_factor.h"
#include "zaber/motion/dto/ascii/device_identity.h"
#include "zaber/motion/dto/ascii/device_io_info.h"
#include "zaber/motion/dto/ascii/digital_output_action.h"
#include "zaber/motion/dto/ascii/get_axis_setting.h"
#include "zaber/motion/dto/ascii/get_axis_setting_result.h"
#include "zaber/motion/dto/ascii/get_setting.h"
#include "zaber/motion/dto/ascii/get_setting_result.h"
#include "zaber/motion/dto/ascii/io_port_label.h"
#include "zaber/motion/dto/ascii/io_port_type.h"
#include "zaber/motion/dto/ascii/lockstep_axes.h"
#include "zaber/motion/dto/ascii/message_type.h"
#include "zaber/motion/dto/ascii/oscilloscope_capture_properties.h"
#include "zaber/motion/dto/ascii/oscilloscope_data_source.h"
#include "zaber/motion/dto/ascii/paramset_info.h"
#include "zaber/motion/dto/ascii/pid_tuning.h"
#include "zaber/motion/dto/ascii/pvt_axis_definition.h"
#include "zaber/motion/dto/ascii/pvt_axis_type.h"
#include "zaber/motion/dto/ascii/pvt_mode.h"
#include "zaber/motion/dto/ascii/response.h"
#include "zaber/motion/dto/ascii/servo_tuning_param.h"
#include "zaber/motion/dto/ascii/servo_tuning_paramset.h"
#include "zaber/motion/dto/ascii/simple_tuning.h"
#include "zaber/motion/dto/ascii/simple_tuning_param_definition.h"
#include "zaber/motion/dto/ascii/stream_axis_definition.h"
#include "zaber/motion/dto/ascii/stream_axis_type.h"
#include "zaber/motion/dto/ascii/stream_mode.h"
#include "zaber/motion/dto/ascii/trigger_action.h"
#include "zaber/motion/dto/ascii/trigger_condition.h"
#include "zaber/motion/dto/ascii/trigger_enabled_state.h"
#include "zaber/motion/dto/ascii/trigger_operation.h"
#include "zaber/motion/dto/ascii/trigger_state.h"
#include "zaber/motion/dto/ascii/unknown_response_event.h"
