// ===== THIS FILE IS GENERATED FROM A TEMPLATE ===== //
// ============== DO NOT EDIT DIRECTLY ============== //


#pragma once

#if !defined(ZML_INCLUDES_H)
#define ZML_INCLUDES_H

#include "zaber/motion/dto/includes.h"
#include "zaber/motion/exceptions/bad_command_exception.h"
#include "zaber/motion/exceptions/bad_data_exception.h"
#include "zaber/motion/exceptions/binary_command_failed_exception.h"
#include "zaber/motion/exceptions/command_failed_exception.h"
#include "zaber/motion/exceptions/command_preempted_exception.h"
#include "zaber/motion/exceptions/command_too_long_exception.h"
#include "zaber/motion/exceptions/connection_closed_exception.h"
#include "zaber/motion/exceptions/connection_failed_exception.h"
#include "zaber/motion/exceptions/conversion_failed_exception.h"
#include "zaber/motion/exceptions/convert_exception.h"
#include "zaber/motion/exceptions/device_address_conflict_exception.h"
#include "zaber/motion/exceptions/device_busy_exception.h"
#include "zaber/motion/exceptions/device_db_failed_exception.h"
#include "zaber/motion/exceptions/device_detection_failed_exception.h"
#include "zaber/motion/exceptions/device_failed_exception.h"
#include "zaber/motion/exceptions/device_not_identified_exception.h"
#include "zaber/motion/exceptions/driver_disabled_exception.h"
#include "zaber/motion/exceptions/g_code_execution_exception.h"
#include "zaber/motion/exceptions/g_code_syntax_exception.h"
#include "zaber/motion/exceptions/incompatible_shared_library_exception.h"
#include "zaber/motion/exceptions/internal_error_exception.h"
#include "zaber/motion/exceptions/invalid_argument_exception.h"
#include "zaber/motion/exceptions/invalid_data_exception.h"
#include "zaber/motion/exceptions/invalid_operation_exception.h"
#include "zaber/motion/exceptions/invalid_packet_exception.h"
#include "zaber/motion/exceptions/invalid_park_state_exception.h"
#include "zaber/motion/exceptions/invalid_request_data_exception.h"
#include "zaber/motion/exceptions/invalid_response_exception.h"
#include "zaber/motion/exceptions/io_channel_out_of_range_exception.h"
#include "zaber/motion/exceptions/io_failed_exception.h"
#include "zaber/motion/exceptions/lockstep_enabled_exception.h"
#include "zaber/motion/exceptions/lockstep_not_enabled_exception.h"
#include "zaber/motion/exceptions/motion_lib_exception.h"
#include "zaber/motion/exceptions/movement_failed_exception.h"
#include "zaber/motion/exceptions/movement_interrupted_exception.h"
#include "zaber/motion/exceptions/no_device_found_exception.h"
#include "zaber/motion/exceptions/no_value_for_key_exception.h"
#include "zaber/motion/exceptions/not_supported_exception.h"
#include "zaber/motion/exceptions/operation_failed_exception.h"
#include "zaber/motion/exceptions/os_failed_exception.h"
#include "zaber/motion/exceptions/out_of_request_ids_exception.h"
#include "zaber/motion/exceptions/pvt_discontinuity_exception.h"
#include "zaber/motion/exceptions/pvt_execution_exception.h"
#include "zaber/motion/exceptions/pvt_mode_exception.h"
#include "zaber/motion/exceptions/pvt_movement_failed_exception.h"
#include "zaber/motion/exceptions/pvt_movement_interrupted_exception.h"
#include "zaber/motion/exceptions/pvt_setup_failed_exception.h"
#include "zaber/motion/exceptions/remote_mode_exception.h"
#include "zaber/motion/exceptions/request_timeout_exception.h"
#include "zaber/motion/exceptions/serial_port_busy_exception.h"
#include "zaber/motion/exceptions/set_device_state_failed_exception.h"
#include "zaber/motion/exceptions/set_peripheral_state_failed_exception.h"
#include "zaber/motion/exceptions/setting_not_found_exception.h"
#include "zaber/motion/exceptions/stream_discontinuity_exception.h"
#include "zaber/motion/exceptions/stream_execution_exception.h"
#include "zaber/motion/exceptions/stream_mode_exception.h"
#include "zaber/motion/exceptions/stream_movement_failed_exception.h"
#include "zaber/motion/exceptions/stream_movement_interrupted_exception.h"
#include "zaber/motion/exceptions/stream_setup_failed_exception.h"
#include "zaber/motion/exceptions/timeout_exception.h"
#include "zaber/motion/exceptions/transport_already_used_exception.h"
#include "zaber/motion/exceptions/unknown_request_exception.h"
#include "zaber/motion/library.h"
#include "zaber/motion/library_exception.h"
#include "zaber/motion/tools.h"
#include "zaber/motion/unit_table.h"
#include "zaber/motion/units.h"
#include "zaber/motion/version.h"

#endif
